# Generated by Django 6.0.3 on 2026-04-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="state",
        ),
    ]
