# Generated by Django 6.0.3 on 2026-04-19 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_address_remove_profile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
