# Generated by Django 6.0.3 on 2026-04-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="media/categories/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="media/products_images/"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(upload_to="media/restaurants/"),
        ),
    ]
