# Generated by Django 6.0.3 on 2026-04-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_category_image_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="categories/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products_images/"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(upload_to="restaurants/"),
        ),
    ]
