# Generated by Django 6.0.3 on 2026-04-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_created_at_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_description",
            field=models.TextField(null=True),
        ),
    ]
