# Generated by Django 6.0.3 on 2026-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_restaurant_restaurant_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="restaurant_description",
            field=models.TextField(),
        ),
    ]
