# Generated by Django 6.0.3 on 2026-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_restaurant_restaurant_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="closed_hours",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="opening_hours",
            field=models.TextField(null=True),
        ),
    ]
