# Generated by Django 6.0.3 on 2026-04-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_restaurant_closed_hours_restaurant_opening_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="closed_hours",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="opening_hours",
            field=models.TextField(),
        ),
    ]
