# Generated by Django 6.0.3 on 2026-04-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_restaurant_closed_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="time_to_deliver",
            field=models.TextField(null=True),
        ),
    ]
